export const INJECTION_TOKENS = {
    USER_REPOSITORY: 'USER_REPOSITORY',
    PRODUCT_REPOSITORY: 'PRODUCT_REPOSITORY',
    ORDER_REPOSITORY: 'ORDER_REPOSITORY',
    CATEGORY_REPOSITORY: 'CATEGORY_REPOSITORY',
    COUNTRY_REPOSITORY: 'COUNTRY_REPOSITORY',
    ADDRESS_REPOSITORY: 'ADDRESS_REPOSITORY',
    AUTH_SERVICE: 'AUTH_SERVICE',
    FILE_UPLOAD_SERVICE: 'FILE_UPLOAD_SERVICE',
    PAYPAL_SERVICE: 'PAYPAL_SERVICE',
} as const;
